import importlib
import pytest

MODULES = [
    "dbgpt_analyst",
    "dbgpt_analyst.config",
    "dbgpt_analyst.common.db",
    "dbgpt_analyst.common.redis_client",
    "dbgpt_analyst.common.duckdb_client",
    "dbgpt_analyst.common.cache",
    "dbgpt_analyst.common.feature_flags",
    "dbgpt_analyst.common.langfuse_client",
    "dbgpt_analyst.common.llm_factory",
    "dbgpt_analyst.common.model_fallback",
    "dbgpt_analyst.common.prompt_hub",
    "dbgpt_analyst.common.resilience",
    "dbgpt_analyst.common.sql_guard",
    "dbgpt_analyst.common.workspace_manager",
    "dbgpt_analyst.core.cache",
    "dbgpt_analyst.core.envelope",
    "dbgpt_analyst.core.helpers",
    "dbgpt_analyst.core.state",
    "dbgpt_analyst.events",
    "dbgpt_analyst.events_schemas",
    "dbgpt_analyst.libs.react_agent",
    "dbgpt_analyst.libs.bi.connections",
    "dbgpt_analyst.libs.bi.introspection",
    "dbgpt_analyst.libs.bi.schema_cache",
    "dbgpt_analyst.libs.bi.federation",
    "dbgpt_analyst.libs.bi.query_cache",
    "dbgpt_analyst.libs.bi.relationship_discovery",
    "dbgpt_analyst.libs.bi.temporal_detect",
    "dbgpt_analyst.libs.bi.dataset_diff",
    "dbgpt_analyst.libs.bi.data_sync",
    "dbgpt_analyst.libs.bi.formula_report",
    "dbgpt_analyst.libs.bi.mock_data",
    "dbgpt_analyst.adapters.bi_platform",
    "dbgpt_analyst.adapters.db_engine.base",
    "dbgpt_analyst.adapters.db_engine.postgres",
    "dbgpt_analyst.adapters.db_engine.sqlite",
    "dbgpt_analyst.main_agent",
    "dbgpt_analyst.middleware.approval_policy",
    "dbgpt_analyst.middleware.db_circuit_breaker",
    "dbgpt_analyst.middleware.doom_loop_guard",
    "dbgpt_analyst.middleware.dynamic_injection",
    "dbgpt_analyst.middleware.ensure_no_empty_msg",
    "dbgpt_analyst.middleware.messages_reducer",
    "dbgpt_analyst.middleware.runtime",
    "dbgpt_analyst.middleware.sanitize_tool_inputs",
    "dbgpt_analyst.middleware.skills",
    "dbgpt_analyst.middleware.thinking_guard",
    "dbgpt_analyst.middleware.tool_error_handler",
    "dbgpt_analyst.nodes.analysis",
    "dbgpt_analyst.nodes.data_explorer",
    "dbgpt_analyst.nodes.execution",
    "dbgpt_analyst.nodes.schema_resolver",
    "dbgpt_analyst.nodes.sql_generator",
    "dbgpt_analyst.nodes.sql_planner",
    "dbgpt_analyst.nodes.table_selector",
    "dbgpt_analyst.prompts",
    "dbgpt_analyst.subgraphs.sql_agent_subgraph",
    "dbgpt_analyst.subgraphs.data_engineer_subgraph",
    "dbgpt_analyst.subgraphs.synthesizer_subgraph",
    "dbgpt_analyst.subgraphs.diagnostic_subgraph",
    "dbgpt_analyst.subgraphs.report_subgraph",
    "dbgpt_analyst.subgraphs.report_graph",
    "dbgpt_analyst.subgraphs.web_researcher_graph",
    "dbgpt_analyst.subgraphs.modes.quick_analysis_subgraph",
    "dbgpt_analyst.subgraphs.modes.deep_report_subgraph",
    "dbgpt_analyst.subgraphs.modes.hybrid_analysis_subgraph",
    "dbgpt_analyst.subgraphs.modes.web_research_subgraph",
    "dbgpt_analyst.subgraphs.modes.office_writer_subgraph",
    "dbgpt_analyst.tools.explore_toolkit",
    "dbgpt_analyst.tools.research_toolkit",
    "dbgpt_analyst.tools.workspace_tools",
]


@pytest.mark.parametrize("mod_name", MODULES)
def test_import_module(mod_name):
    mod = importlib.import_module(mod_name)
    assert mod is not None
