"""middleware/verification_gate.py — Backward-compatible re-export from guard.verification_gate."""
from dbgpt_analyst.guard.verification_gate import (
    VerificationGateMiddleware,
    _DATE_PATTERN,
    _IDENTIFIER_PATTERN,
    _MONTH_PATTERN,
    _NUMBER_PATTERN,
    _QUARTER_PATTERN,
    _STEP_PATTERN,
    _TOP_K_PATTERN,
    _YEAR_PATTERN,
    _extract_ground_truth_values,
    _is_benign_label,
    _parse_number_value,
    compute_metric,
    format_number,
    inject_grounded_facts,
    strip_ungrounded_claims,
    verify_numerical_claims,
)

__all__ = [
    "VerificationGateMiddleware",
    "_DATE_PATTERN",
    "_IDENTIFIER_PATTERN",
    "_MONTH_PATTERN",
    "_NUMBER_PATTERN",
    "_QUARTER_PATTERN",
    "_STEP_PATTERN",
    "_TOP_K_PATTERN",
    "_YEAR_PATTERN",
    "_extract_ground_truth_values",
    "_is_benign_label",
    "_parse_number_value",
    "compute_metric",
    "format_number",
    "inject_grounded_facts",
    "strip_ungrounded_claims",
    "verify_numerical_claims",
]
