"""events package — SSE Streaming Envelope Events and Artifact Protocols.

Modular subpackages:
  - runtime/   → StreamState, DualFormatStreamAdapter, EventEmitter, DurableSessionState, session_fold
  - shared/    → Shared Universal Event Payload Schemas
  - thinking/  → CoT thinking token streaming
  - planning/  → Planning and HITL steering events
  - tool_execution/ → Tool lifecycle and evidence events
  - artifacts/ → Office & Analytics artifact streaming events
"""

from dbgpt_analyst.events.artifact_events import (
    ArtifactEvent,
    ArtifactPhase,
    ArtifactRenderEvent,
    ArtifactStream,
    ChartConfig,
    ChartData,
    ExcalidrawElement,
)
from dbgpt_analyst.events.base import BaseEvent, emit_custom
from dbgpt_analyst.events.lifecycle_events import (
    CheckpointSavedEvent,
    NodeEndEvent,
    NodeStartEvent,
    RunEndEvent,
    RunStartEvent,
    SessionEvictedEvent,
)
from dbgpt_analyst.events.schemas_stream import (
    AgentStreamEvent,
    dict_to_xml,
    dict_to_xml_sse,
    event_to_sse,
    event_to_xml_sse,
    parse_sse_events,
    xml_cdata,
    xml_to_dict,
)
from dbgpt_analyst.events.streaming_events import (
    AnswerDeltaEvent,
    ApprovalRequestEvent,
    ChartSpecEvent,
    ClarificationNeededEvent,
    ErrorEvent,
    FinalEvent,
    FollowupQuestionsEvent,
    IntentDetectedEvent,
    JoinPathEvent,
    MemoryRecalledEvent,
    MemoryStoredEvent,
    PhaseEvent,
    PlanEvent,
    PlanStepEvent,
    PolicyCheckedEvent,
    ReasoningEvent,
    ReflectionEvent,
    RowBatchEvent,
    SchemaEnrichedEvent,
    SourceMetaEvent,
    SQLDeltaEvent,
    SQLPlanDeltaEvent,
    SQLValidatedEvent,
    StatusEvent,
    SubagentEvent,
    TableConsideredEvent,
    TableSelectedEvent,
    TextPartEvent,
    ThinkingDeltaEvent,
    ThinkPartEvent,
    ToolCallEvent,
    ToolResultEvent,
    TurnEndEvent,
)
from dbgpt_analyst.events.task_events import (
    ClientEffectEvent,
    StructuredInputEvent,
    TaskCallEvent,
    WorkflowTaskEvent,
)

# ─── New Senior Staff SSE & Session Fold Exports ───────────────────────────
from .runtime import (
    StreamState,
    DualFormatStreamAdapter,
    StreamFormat,
    EventEmitter,
    RunStatus,
    TERMINAL_STATUSES,
    STREAM_TERMINAL_STATUSES,
    ABSORBING_TERMINAL_STATUSES,
    EVENT_TYPES,
    DurableSessionState,
    SessionEvent,
    SessionStatus,
    extract_semantic_xml_blocks,
    extract_semantic_tags,
    foldEvent,
    foldEvents,
    fold_event,
    fold_events,
    format_clause_xml,
    format_contract_xml,
    format_thought_xml,
    format_tool_xml,
    resume_session,
)
from .shared import (
    BaseEventPayload,
    ThinkingPayload,
    ThinkingDonePayload,
    TodoItemSchema,
    TodosUpdatePayload,
    SubagentStartPayload,
    SubagentTokenPayload,
    SubagentCompletePayload,
    SkillLoadedPayload,
    AuditCardPayload,
)
from . import runtime, shared, thinking, planning, tool_execution, artifacts

__all__ = [
    # Legacy & Existing Schemas
    "AgentStreamEvent",
    "AnswerDeltaEvent",
    "ApprovalRequestEvent",
    "ArtifactEvent",
    "ArtifactPhase",
    "ArtifactRenderEvent",
    "ArtifactStream",
    "BaseEvent",
    "ChartConfig",
    "ChartData",
    "ChartSpecEvent",
    "CheckpointSavedEvent",
    "ClarificationNeededEvent",
    "ClientEffectEvent",
    "ErrorEvent",
    "ExcalidrawElement",
    "FinalEvent",
    "FollowupQuestionsEvent",
    "IntentDetectedEvent",
    "JoinPathEvent",
    "MemoryRecalledEvent",
    "MemoryStoredEvent",
    "NodeEndEvent",
    "NodeStartEvent",
    "PhaseEvent",
    "PlanEvent",
    "PlanStepEvent",
    "PolicyCheckedEvent",
    "ReasoningEvent",
    "ReflectionEvent",
    "RowBatchEvent",
    "RunEndEvent",
    "RunStartEvent",
    "SQLDeltaEvent",
    "SQLPlanDeltaEvent",
    "SQLValidatedEvent",
    "SchemaEnrichedEvent",
    "SessionEvictedEvent",
    "SourceMetaEvent",
    "StatusEvent",
    "StructuredInputEvent",
    "SubagentEvent",
    "TableConsideredEvent",
    "TableSelectedEvent",
    "TaskCallEvent",
    "TextPartEvent",
    "ThinkPartEvent",
    "ThinkingDeltaEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "TurnEndEvent",
    "WorkflowTaskEvent",
    "dict_to_xml",
    "dict_to_xml_sse",
    "emit_custom",
    "event_to_sse",
    "event_to_xml_sse",
    "parse_sse_events",
    "xml_cdata",
    "xml_to_dict",
    # Senior Staff Modular Architecture
    "StreamState",
    "DualFormatStreamAdapter",
    "StreamFormat",
    "EventEmitter",
    "RunStatus",
    "TERMINAL_STATUSES",
    "STREAM_TERMINAL_STATUSES",
    "ABSORBING_TERMINAL_STATUSES",
    "EVENT_TYPES",
    "DurableSessionState",
    "SessionEvent",
    "SessionStatus",
    "extract_semantic_xml_blocks",
    "extract_semantic_tags",
    "foldEvent",
    "foldEvents",
    "fold_event",
    "fold_events",
    "format_clause_xml",
    "format_contract_xml",
    "format_thought_xml",
    "format_tool_xml",
    "resume_session",
    "BaseEventPayload",
    "ThinkingPayload",
    "ThinkingDonePayload",
    "TodoItemSchema",
    "TodosUpdatePayload",
    "SubagentStartPayload",
    "SubagentTokenPayload",
    "SubagentCompletePayload",
    "SkillLoadedPayload",
    "AuditCardPayload",
    "runtime",
    "shared",
    "thinking",
    "planning",
    "tool_execution",
    "artifacts",
]
